# Generated by Django 5.1 on 2024-08-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
    ]
