# Generated by Django 5.1 on 2024-08-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tasks_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
